FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: cli_a25967705178d013
  FEISHU_APP_SECRET: BmmBaVg5uL3yr6edzI4zDp1uN64Aj8j5
APP_TOKEN_CACHE_KEY: APP_TOKEN_CACHE_KEY
MONGODB_CONFIG:
  name: "gateway-nest"          # 自定义次数据库链接名称
  type: mongodb                      # 数据库链接类型
  url: "mongodb://localhost:27017"   # 数据库链接地址
  username: "admin"                   # 数据库链接用户名
  password: "123456"                 # 数据库链接密码
  database: "gateway-nest"      # 数据库名
  entities: "mongo"                  # 自定义加载类型
  logging: false                     # 数据库打印日志
  synchronize: true                  # 是否开启同步数据表功能
REDIS_CONFIG:
  host: "localhost"  # redis 链接
  port: 6379         # redis 端口
  auth: "xxxx"       # redis 连接密码
  db: 1              # redis 数据库